# Generated by Django 4.1.13 on 2024-10-19 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminside', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logo',
            name='logo_image',
        ),
        migrations.RemoveField(
            model_name='logo',
            name='uploaded_at',
        ),
        migrations.AddField(
            model_name='logo',
            name='image',
            field=models.ImageField(default='', upload_to='logo/'),
            preserve_default=False,
        ),
    ]
