# Generated by Django 4.1.13 on 2024-10-03 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_product_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='images',
        ),
    ]
