# Generated by Django 4.1.13 on 2024-10-31 20:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminside', '0003_category'),
        ('myapp', '0008_remove_product_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='products', to='adminside.category'),
            preserve_default=False,
        ),
    ]
